In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("seasonal_agriculture_performance_cleaned.csv")
print("Dataset loaded successfully.")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully.
Rows: 3968
Columns: 28

In [6]:
df.head()

,Farm_ID,State,District,Crop,Season,Farm_Area_Hectares,Rainfall_mm,Avg_Temperature_C,Humidity_pct,Sunlight_Hours_Day,...,Seed_Quality_Score,Yield_Tonnes_Ha,Production_Tonnes,Market_Price_INR_Tonne,Total_Cost_INR,Revenue_INR,Profit_INR,Water_Used_m3,Water_Efficiency_t_per_1000m3,Disease_Pest_Risk_pct
0,SF10001,Andhra Pradesh,Rajkot,Wheat,Kharif,0.53,486.4,24.3,69.1,5.8,...,0.76,2.46,1.30,23700,42662,30810,-11852,237,5.485,55.3
1,SF10002,Maharashtra,Nalgonda,Maize,Kharif,6.53,855.4,25.7,78.4,5.1,...,0.94,0.30,1.96,20613,492351,40401,-451950,4953,0.396,49.9
2,SF10003,Telangana,Warangal,Pulses,Rabi,4.86,455.6,23.9,56.4,10.3,...,0.98,0.52,2.53,75283,315210,190466,-124744,1275,1.984,33.7
3,SF10004,Telangana,Indore,Rice,Kharif,4.50,753.2,29.7,65.2,6.3,...,0.74,1.84,8.28,24244,296444,200740,-95704,3834,2.160,50.6
4,SF10005,Karnataka,Ludhiana,Maize,Zaid,4.21,101.6,34.1,55.2,6.5,...,0.90,2.21,9.30,20818,337959,193607,-144352,3287,2.829,32.3

In [7]:
df.shape

(3968, 28)

In [8]:
df.columns.tolist()

['Farm_ID',
 'State',
 'District',
 'Crop',
 'Season',
 'Farm_Area_Hectares',
 'Rainfall_mm',
 'Avg_Temperature_C',
 'Humidity_pct',
 'Sunlight_Hours_Day',
 'Soil_pH',
 'Soil_Moisture_pct',
 'Nitrogen_kg_ha',
 'Phosphorus_kg_ha',
 'Potassium_kg_ha',
 'Irrigation_Method',
 'Fertilizer_kg_ha',
 'Pesticide_Litre_ha',
 'Seed_Quality_Score',
 'Yield_Tonnes_Ha',
 'Production_Tonnes',
 'Market_Price_INR_Tonne',
 'Total_Cost_INR',
 'Revenue_INR',
 'Profit_INR',
 'Water_Used_m3',
 'Water_Efficiency_t_per_1000m3',
 'Disease_Pest_Risk_pct']

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3968 entries, 0 to 3967
Data columns (total 28 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Farm_ID                        3968 non-null   str
 1   State                          3968 non-null   str
 2   District                       3968 non-null   str
 3   Crop                           3968 non-null   str
 4   Season                         3968 non-null   str
 5   Farm_Area_Hectares             3968 non-null   float64
 6   Rainfall_mm                    3968 non-null   float64
 7   Avg_Temperature_C              3968 non-null   float64
 8   Humidity_pct                   3968 non-null   float64
 9   Sunlight_Hours_Day             3968 non-null   float64
 10  Soil_pH                        3968 non-null   float64
 11  Soil_Moisture_pct              3968 non-null   float64
 12  Nitrogen_kg_ha                 3968 non-null   float64
 13  Phosphorus_kg_ha               3968 non-null   float64
 14  Potassium_kg_ha                3968 non-null   float64
 15  Irrigation_Method              3968 non-null   str
 16  Fertilizer_kg_ha               3968 non-null   float64
 17  Pesticide_Litre_ha             3968 non-null   float64
 18  Seed_Quality_Score             3968 non-null   float64
 19  Yield_Tonnes_Ha                3968 non-null   float64
 20  Production_Tonnes              3968 non-null   float64
 21  Market_Price_INR_Tonne         3968 non-null   int64
 22  Total_Cost_INR                 3968 non-null   int64
 23  Revenue_INR                    3968 non-null   int64
 24  Profit_INR                     3968 non-null   int64
 25  Water_Used_m3                  3968 non-null   int64
 26  Water_Efficiency_t_per_1000m3  3968 non-null   float64
 27  Disease_Pest_Risk_pct          3968 non-null   float64
dtypes: float64(17), int64(5), str(6)
memory usage: 868.1 KB

In [10]:
df.describe()

,Farm_Area_Hectares,Rainfall_mm,Avg_Temperature_C,Humidity_pct,Sunlight_Hours_Day,Soil_pH,Soil_Moisture_pct,Nitrogen_kg_ha,Phosphorus_kg_ha,Potassium_kg_ha,...,Seed_Quality_Score,Yield_Tonnes_Ha,Production_Tonnes,Market_Price_INR_Tonne,Total_Cost_INR,Revenue_INR,Profit_INR,Water_Used_m3,Water_Efficiency_t_per_1000m3,Disease_Pest_Risk_pct
count,3968.000000,3968.000000,3968.000000,3968.000000,3968.000000,3968.000000,3968.000000,3968.000000,3968.000000,3968.000000,...,3968.000000,3968.000000,3968.000000,3968.000000,3.968000e+03,3.968000e+03,3.968000e+03,3968.000000,3968.000000,3968.000000
mean,7.890635,601.310648,26.829007,63.258871,7.322984,6.700726,26.528125,120.203075,57.803427,104.714138,...,0.825945,5.270595,43.291411,44683.893145,5.262634e+05,6.381355e+05,1.118721e+05,6038.882308,5.394143,46.406552
std,4.223316,288.331190,3.814200,11.966047,1.123313,0.640810,6.692572,31.167185,17.011902,27.732855,...,0.101791,13.361398,127.073838,30241.212184,2.941955e+05,6.373426e+05,5.457427e+05,5567.510646,8.845745,12.422480
min,0.500000,80.000000,16.200000,25.000000,3.500000,5.200000,8.000000,40.000000,15.000000,30.000000,...,0.650000,0.300000,0.150000,2594.000000,2.682600e+04,6.107000e+03,-1.019223e+06,128.000000,0.135000,5.000000
25%,4.260000,370.850000,24.000000,54.900000,6.600000,6.260000,21.800000,98.500000,46.300000,86.175000,...,0.730000,1.050000,5.040000,21423.500000,2.748018e+05,2.091222e+05,-1.492672e+05,2263.000000,1.665250,37.300000
50%,7.905000,582.050000,27.000000,63.100000,7.300000,6.690000,26.500000,120.050000,57.500000,105.100000,...,0.830000,1.740000,11.830000,25913.000000,5.193130e+05,4.568305e+05,3.419000e+03,4433.500000,2.949000,46.400000
75%,11.650000,837.225000,29.600000,72.000000,8.100000,7.140000,31.300000,141.200000,69.400000,123.500000,...,0.910000,2.840000,24.380000,68262.500000,7.618188e+05,8.348798e+05,2.161878e+05,7828.250000,5.155750,55.000000
max,15.000000,1395.200000,39.700000,95.000000,11.000000,8.400000,47.000000,220.000000,120.000000,200.000000,...,1.000000,101.440000,1424.400000,131240.000000,1.349990e+06,5.080900e+06,4.345421e+06,40902.000000,79.800000,88.900000

In [11]:
missing_values = df.isnull().sum()
missing_values[missing_values > 0]

Series([], dtype: int64)

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df['Season'].value_counts()

Season
Kharif    1772
Rabi      1607
Zaid       589
Name: count, dtype: int64

In [15]:
df['Crop'].value_counts()

Crop
Rice         682
Wheat        612
Maize        547
Cotton       504
Pulses       494
Groundnut    419
Chilli       407
Sugarcane    303
Name: count, dtype: int64

In [16]:
df['State'].value_counts()

State
Andhra Pradesh    525
Telangana         511
Maharashtra       510
Madhya Pradesh    491
Punjab            484
Karnataka         483
Gujarat           483
Tamil Nadu        481
Name: count, dtype: int64

In [17]:
df['Irrigation_Method'].value_counts()

Irrigation_Method
Flood        1296
Rainfed      1037
Drip          907
Sprinkler     728
Name: count, dtype: int64

In [18]:
# Fill missing Rainfall using the median of the corresponding Season
rainfall_medians = df.groupby('Season')['Rainfall_mm'].median()
df['Rainfall_mm'] = df['Rainfall_mm'].fillna(
    df.groupby('Season')['Rainfall_mm'].transform('median')
)
print("Missing Rainfall values before:", 48)
print("Missing Rainfall values after:", df['Rainfall_mm'].isnull().sum())
print("\nSeason-wise medians used:")
print(rainfall_medians)

Missing Rainfall values before: 48
Missing Rainfall values after: 0

Season-wise medians used:
Season
Kharif    854.75
Rabi      430.30
Zaid      283.30
Name: Rainfall_mm, dtype: float64

In [19]:

soil_medians = df.groupby('Season')['Soil_Moisture_pct'].median()
df['Soil_Moisture_pct'] = df['Soil_Moisture_pct'].fillna(
    df.groupby('Season')['Soil_Moisture_pct'].transform('median')
)
print("Missing Soil Moisture values before:", 40)
print("Missing Soil Moisture values after:", df['Soil_Moisture_pct'].isnull().sum())
print("\nSeason-wise medians used:")
print(soil_medians)

Missing Soil Moisture values before: 40
Missing Soil Moisture values after: 0

Season-wise medians used:
Season
Kharif    31.2
Rabi      24.0
Zaid      19.1
Name: Soil_Moisture_pct, dtype: float64

In [20]:

rows_before = len(df)
df = df.dropna(subset=['Yield_Tonnes_Ha']).copy()
rows_after = len(df)

print("Rows before removing missing Yield:", rows_before)
print("Rows removed:", rows_before - rows_after)
print("Rows after cleaning Yield:", rows_after)

Rows before removing missing Yield: 3968
Rows removed: 0
Rows after cleaning Yield: 3968

In [21]:

text_columns = df.select_dtypes(include='object').columns
for col in text_columns:
    df[col] = df[col].str.strip()

print("Text columns standardized:", list(text_columns))

Text columns standardized: ['Farm_ID', 'State', 'District', 'Crop', 'Season', 'Irrigation_Method']

C:\Users\tanwa\AppData\Local\Temp\ipykernel_7520\326950795.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include='object').columns

In [22]:
final_missing = df.isnull().sum()
final_missing[final_missing > 0]

Series([], dtype: int64)

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.shape

(3968, 28)

In [25]:
df.to_csv("seasonal_agriculture_performance_cleaned.csv", index=False)
print("Cleaned dataset saved successfully.")
print("File: seasonal_agriculture_performance_cleaned.csv")

Cleaned dataset saved successfully.
File: seasonal_agriculture_performance_cleaned.csv